namespace Mycobank.Services.Search.Enums
{
    public enum MycobankLiteratureSearchField
    {
        _id,
        Abstract,
        Authors,
        CreationDate,
        Documenttype,
        DOI,
        Edition,
        Editors,
        FirstPage,
        Hyperlink,
        Hyperlink2,
        ISBN,
        Issue,
        JournalName,
        Keywords,
        LastModificationDate,
        LastModificationUser,
        LastPage,
        Name,
        Publisher,
        PubMedID,
        Series,
        Summary,
        Title,
        TitleAbbreviated,
        User,
        Volume,
        Year
    }
}
